package com.xiaobaidu.mall.entity;

import java.util.Date;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.image_url
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.link_url
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.description
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String description;


    private int pos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.id
     *
     * @param id the value for banner.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.image_url
     *
     * @return the value of banner.image_url
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.image_url
     *
     * @param imageUrl the value for banner.image_url
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.link_url
     *
     * @return the value of banner.link_url
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.link_url
     *
     * @param linkUrl the value for banner.link_url
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.description
     *
     * @return the value of banner.description
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.description
     *
     * @param description the value for banner.description
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.creator
     *
     * @return the value of banner.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.creator
     *
     * @param creator the value for banner.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.create_time
     *
     * @return the value of banner.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.create_time
     *
     * @param createTime the value for banner.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.update_time
     *
     * @return the value of banner.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.update_time
     *
     * @param updateTime the value for banner.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public int getPos() {
        return pos;
    }

    public void setPos(int pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", linkUrl=").append(linkUrl);
        sb.append(", description=").append(description);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}