package com.xiaobaidu.mall.entity;

import java.util.Date;

public class CommType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.pid
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.hot
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Integer hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_type.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.id
     *
     * @return the value of comm_type.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.id
     *
     * @param id the value for comm_type.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.pid
     *
     * @return the value of comm_type.pid
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.pid
     *
     * @param pid the value for comm_type.pid
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.name
     *
     * @return the value of comm_type.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.name
     *
     * @param name the value for comm_type.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.hot
     *
     * @return the value of comm_type.hot
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.hot
     *
     * @param hot the value for comm_type.hot
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.image
     *
     * @return the value of comm_type.image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.image
     *
     * @param image the value for comm_type.image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.creator
     *
     * @return the value of comm_type.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.creator
     *
     * @param creator the value for comm_type.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.create_time
     *
     * @return the value of comm_type.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.create_time
     *
     * @param createTime the value for comm_type.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_type.update_time
     *
     * @return the value of comm_type.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_type.update_time
     *
     * @param updateTime the value for comm_type.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_type
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", name=").append(name);
        sb.append(", hot=").append(hot);
        sb.append(", image=").append(image);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}