package com.xiaobaidu.mall.entity;

import java.util.Date;

public class CommThemeEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.comm_type
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String commType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.introduce
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.start_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.end_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.status
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_theme_event.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.id
     *
     * @return the value of comm_theme_event.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.id
     *
     * @param id the value for comm_theme_event.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.comm_type
     *
     * @return the value of comm_theme_event.comm_type
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCommType() {
        return commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.comm_type
     *
     * @param commType the value for comm_theme_event.comm_type
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCommType(String commType) {
        this.commType = commType == null ? null : commType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.name
     *
     * @return the value of comm_theme_event.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.name
     *
     * @param name the value for comm_theme_event.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.introduce
     *
     * @return the value of comm_theme_event.introduce
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.introduce
     *
     * @param introduce the value for comm_theme_event.introduce
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.image
     *
     * @return the value of comm_theme_event.image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.image
     *
     * @param image the value for comm_theme_event.image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.start_time
     *
     * @return the value of comm_theme_event.start_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.start_time
     *
     * @param startTime the value for comm_theme_event.start_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.end_time
     *
     * @return the value of comm_theme_event.end_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.end_time
     *
     * @param endTime the value for comm_theme_event.end_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.status
     *
     * @return the value of comm_theme_event.status
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.status
     *
     * @param status the value for comm_theme_event.status
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.creator
     *
     * @return the value of comm_theme_event.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.creator
     *
     * @param creator the value for comm_theme_event.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.create_time
     *
     * @return the value of comm_theme_event.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.create_time
     *
     * @param createTime the value for comm_theme_event.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_theme_event.update_time
     *
     * @return the value of comm_theme_event.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_theme_event.update_time
     *
     * @param updateTime the value for comm_theme_event.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_theme_event
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", commType=").append(commType);
        sb.append(", name=").append(name);
        sb.append(", introduce=").append(introduce);
        sb.append(", image=").append(image);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", status=").append(status);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}