package com.xiaobaidu.mall.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.hot
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Integer hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.sell_price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private BigDecimal sellPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.price_unit
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String priceUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.type_id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.introduce
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.code
     *
     * @return the value of commodity.code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.code
     *
     * @param code the value for commodity.code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.hot
     *
     * @return the value of commodity.hot
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.hot
     *
     * @param hot the value for commodity.hot
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.price
     *
     * @return the value of commodity.price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price
     *
     * @param price the value for commodity.price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.sell_price
     *
     * @return the value of commodity.sell_price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.sell_price
     *
     * @param sellPrice the value for commodity.sell_price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.price_unit
     *
     * @return the value of commodity.price_unit
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getPriceUnit() {
        return priceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price_unit
     *
     * @param priceUnit the value for commodity.price_unit
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit == null ? null : priceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.type_id
     *
     * @return the value of commodity.type_id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.type_id
     *
     * @param typeId the value for commodity.type_id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.creator
     *
     * @return the value of commodity.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.creator
     *
     * @param creator the value for commodity.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.create_time
     *
     * @return the value of commodity.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.create_time
     *
     * @param createTime the value for commodity.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.update_time
     *
     * @return the value of commodity.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.update_time
     *
     * @param updateTime the value for commodity.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.introduce
     *
     * @return the value of commodity.introduce
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.introduce
     *
     * @param introduce the value for commodity.introduce
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", hot=").append(hot);
        sb.append(", price=").append(price);
        sb.append(", sellPrice=").append(sellPrice);
        sb.append(", priceUnit=").append(priceUnit);
        sb.append(", typeId=").append(typeId);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", introduce=").append(introduce);
        sb.append("]");
        return sb.toString();
    }
}