package com.xiaobaidu.mall.entity;

import java.util.Date;

public class CommImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String commCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.big_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String bigImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.middle_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String middleImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.small_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String smallImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.icon
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_images.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.id
     *
     * @return the value of comm_images.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.id
     *
     * @param id the value for comm_images.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.comm_code
     *
     * @return the value of comm_images.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCommCode() {
        return commCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.comm_code
     *
     * @param commCode the value for comm_images.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCommCode(String commCode) {
        this.commCode = commCode == null ? null : commCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.big_image
     *
     * @return the value of comm_images.big_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getBigImage() {
        return bigImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.big_image
     *
     * @param bigImage the value for comm_images.big_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setBigImage(String bigImage) {
        this.bigImage = bigImage == null ? null : bigImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.middle_image
     *
     * @return the value of comm_images.middle_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getMiddleImage() {
        return middleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.middle_image
     *
     * @param middleImage the value for comm_images.middle_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setMiddleImage(String middleImage) {
        this.middleImage = middleImage == null ? null : middleImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.small_image
     *
     * @return the value of comm_images.small_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getSmallImage() {
        return smallImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.small_image
     *
     * @param smallImage the value for comm_images.small_image
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setSmallImage(String smallImage) {
        this.smallImage = smallImage == null ? null : smallImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.icon
     *
     * @return the value of comm_images.icon
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.icon
     *
     * @param icon the value for comm_images.icon
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.creator
     *
     * @return the value of comm_images.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.creator
     *
     * @param creator the value for comm_images.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.create_time
     *
     * @return the value of comm_images.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.create_time
     *
     * @param createTime the value for comm_images.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_images.update_time
     *
     * @return the value of comm_images.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_images.update_time
     *
     * @param updateTime the value for comm_images.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_images
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", commCode=").append(commCode);
        sb.append(", bigImage=").append(bigImage);
        sb.append(", middleImage=").append(middleImage);
        sb.append(", smallImage=").append(smallImage);
        sb.append(", icon=").append(icon);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}