package com.xiaobaidu.mall.entity;

import java.util.Date;

public class CommStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String commCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.operation
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Integer operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.count
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.remark
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.id
     *
     * @return the value of comm_stock.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.id
     *
     * @param id the value for comm_stock.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.comm_code
     *
     * @return the value of comm_stock.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCommCode() {
        return commCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.comm_code
     *
     * @param commCode the value for comm_stock.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCommCode(String commCode) {
        this.commCode = commCode == null ? null : commCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.operation
     *
     * @return the value of comm_stock.operation
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.operation
     *
     * @param operation the value for comm_stock.operation
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.count
     *
     * @return the value of comm_stock.count
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.count
     *
     * @param count the value for comm_stock.count
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.remark
     *
     * @return the value of comm_stock.remark
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.remark
     *
     * @param remark the value for comm_stock.remark
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.creator
     *
     * @return the value of comm_stock.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.creator
     *
     * @param creator the value for comm_stock.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.create_time
     *
     * @return the value of comm_stock.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.create_time
     *
     * @param createTime the value for comm_stock.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.update_time
     *
     * @return the value of comm_stock.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.update_time
     *
     * @param updateTime the value for comm_stock.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", commCode=").append(commCode);
        sb.append(", operation=").append(operation);
        sb.append(", count=").append(count);
        sb.append(", remark=").append(remark);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}