package com.xiaobaidu.mall.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ShoppingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String commCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.comm_count
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Integer commCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.comm_sell_price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private BigDecimal commSellPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.id
     *
     * @return the value of shopping_cart.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.id
     *
     * @param id the value for shopping_cart.id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_id
     *
     * @return the value of shopping_cart.user_id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.comm_code
     *
     * @return the value of shopping_cart.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCommCode() {
        return commCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.comm_code
     *
     * @param commCode the value for shopping_cart.comm_code
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCommCode(String commCode) {
        this.commCode = commCode == null ? null : commCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.comm_count
     *
     * @return the value of shopping_cart.comm_count
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Integer getCommCount() {
        return commCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.comm_count
     *
     * @param commCount the value for shopping_cart.comm_count
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCommCount(Integer commCount) {
        this.commCount = commCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.comm_sell_price
     *
     * @return the value of shopping_cart.comm_sell_price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public BigDecimal getCommSellPrice() {
        return commSellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.comm_sell_price
     *
     * @param commSellPrice the value for shopping_cart.comm_sell_price
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCommSellPrice(BigDecimal commSellPrice) {
        this.commSellPrice = commSellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.creator
     *
     * @return the value of shopping_cart.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.creator
     *
     * @param creator the value for shopping_cart.creator
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.create_time
     *
     * @return the value of shopping_cart.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.create_time
     *
     * @param createTime the value for shopping_cart.create_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.update_time
     *
     * @return the value of shopping_cart.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.update_time
     *
     * @param updateTime the value for shopping_cart.update_time
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", commCode=").append(commCode);
        sb.append(", commCount=").append(commCount);
        sb.append(", commSellPrice=").append(commSellPrice);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}