package com.xiaobaidu.mall.dao;

import com.xiaobaidu.mall.entity.Commodity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CommodityMapper extends IQuery {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int insert(Commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    Commodity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    List<Commodity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int updateByPrimaryKey(Commodity record);
}