package com.xiaobaidu.mall.dao;

import com.xiaobaidu.mall.entity.CommThemeEvent;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CommThemeEventMapper extends IQuery {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_theme_event
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_theme_event
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int insert(CommThemeEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_theme_event
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    CommThemeEvent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_theme_event
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    List<CommThemeEvent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_theme_event
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int updateByPrimaryKey(CommThemeEvent record);
}