package com.xiaobaidu.mall.dao;

import com.xiaobaidu.mall.entity.CommStock;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CommStockMapper extends IQuery {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int insert(CommStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    CommStock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    List<CommStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int updateByPrimaryKey(CommStock record);
}