package com.xiaobaidu.mall.dao;

import com.xiaobaidu.mall.entity.ShoppingCart;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ShoppingCartMapper extends IQuery {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int insert(ShoppingCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    ShoppingCart selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    List<ShoppingCart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Thu Sep 14 11:30:14 CST 2017
     */
    int updateByPrimaryKey(ShoppingCart record);
}